"""Phase 7: Cybersecurity Check — prompt-injection defence for generation payloads.

Sits between the human-in-the-loop approval stage (Phase 6) and the Gemini
content-generation call (Phase 8). Applies two zero-cost defences:

1. Heuristic regex scrubbing — drops or redacts known injection phrases.
2. Structural delimiter isolation — wraps surviving social-media text in
   strict XML tags so the downstream LLM treats it as data, not instructions.

The public API exposes a single function:

    sanitized = sanitize_trend_payload(payload, rules)

Input ``payload`` is the dict that Phase 6 produced (trend + example posts +
explainer). Output is a new dict with the same shape but with all free-text
fields scrubbed and wrapped, ready for the Phase 8 generation prompt.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

import yaml

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CybersecViolation:
	"""Records a single injection-pattern match that was scrubbed."""

	field: str          # e.g. "post.text", "post.title"
	pattern: str        # the matched regex pattern string
	matched_text: str   # the verbatim matched substring (truncated at 120 chars)


@dataclass
class SanitizeResult:
	"""Return value from ``sanitize_trend_payload``."""

	payload: dict[str, Any]          # sanitized payload ready for Phase 8
	violations: list[CybersecViolation]  # audit log — empty means clean
	blocked: bool                    # True → payload should NOT proceed to Phase 8

	@property
	def is_clean(self) -> bool:
		return not self.blocked


@dataclass
class CybersecRules:
	"""Compiled rules loaded from the YAML config."""

	injection_patterns: list[str]
	max_violations_before_block: int
	compiled: list[re.Pattern[str]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------


def load_cybersec_rules(config_path: str | Path) -> CybersecRules:
	"""Load and compile injection-detection rules from a YAML file."""
	path = Path(config_path)
	if not path.exists():
		raise FileNotFoundError(f"Cybersec config not found: {path}")

	raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
	patterns = _normalize_list(raw.get("injection_patterns", []))
	max_violations = int(raw.get("max_violations_before_block", 3))
	compiled = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in patterns]

	return CybersecRules(
		injection_patterns=patterns,
		max_violations_before_block=max_violations,
		compiled=compiled,
	)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def sanitize_trend_payload(
	payload: dict[str, Any],
	rules: CybersecRules,
) -> SanitizeResult:
	"""Apply prompt-injection defences to a trend payload.

	Steps
	-----
	1. Run heuristic regex scrubbing across all free-text fields.
	2. If violations exceed the configured threshold, mark payload as blocked.
	3. Wrap all surviving social-media text in XML delimiter tags.

	Parameters
	----------
	payload:
		Dict containing ``trend_id``, ``explainer``, and ``example_posts``
		as produced by Phase 6.
	rules:
		Compiled ``CybersecRules`` from ``load_cybersec_rules()``.

	Returns
	-------
	``SanitizeResult`` with the sanitized payload, a list of violations found,
	and a ``blocked`` flag indicating whether Phase 8 should be skipped.
	"""
	violations: list[CybersecViolation] = []

	# Work on a shallow copy so we never mutate the caller's dict.
	sanitized: dict[str, Any] = dict(payload)

	# Scrub the AI explainer text (generated by Phase 6, but still untrusted).
	if sanitized.get("explainer"):
		scrubbed, found = _scrub_text(
			sanitized["explainer"], rules.compiled, field_name="explainer"
		)
		sanitized["explainer"] = scrubbed
		violations.extend(found)

	# Scrub each example post's free-text fields.
	raw_posts: list[dict[str, Any]] = sanitized.get("example_posts", []) or []
	sanitized_posts: list[dict[str, Any]] = []
	for i, post in enumerate(raw_posts):
		post_copy, post_violations = _scrub_post(post, rules.compiled, index=i)
		sanitized_posts.append(post_copy)
		violations.extend(post_violations)
	sanitized["example_posts"] = sanitized_posts

	# Decide whether to block.
	blocked = len(violations) >= rules.max_violations_before_block
	if blocked:
		logger.warning(
			"Cybersec check BLOCKED trend_id=%s — %d violation(s) found",
			sanitized.get("trend_id"),
			len(violations),
		)
	elif violations:
		logger.info(
			"Cybersec check: %d violation(s) scrubbed from trend_id=%s (not blocked)",
			len(violations),
			sanitized.get("trend_id"),
		)

	# Apply XML structural isolation to all surviving free-text.
	if not blocked:
		sanitized = _apply_xml_isolation(sanitized)

	return SanitizeResult(payload=sanitized, violations=violations, blocked=blocked)


# ---------------------------------------------------------------------------
# XML structural delimiter isolation
# ---------------------------------------------------------------------------

_OPEN_TAG = "<untrusted_social_media_data>"
_CLOSE_TAG = "</untrusted_social_media_data>"

# Fields in a post dict that contain raw social-media text.
_POST_TEXT_FIELDS = ("title", "text", "body")


def _apply_xml_isolation(payload: dict[str, Any]) -> dict[str, Any]:
	"""Wrap all free-text fields in XML delimiter tags.

	This signals to the downstream LLM that the enclosed content is
	untrusted user-generated data — not instructions to be executed.
	The caller's dict is NOT mutated; a new dict is returned.
	"""
	result = dict(payload)

	# Wrap the explainer if present (it contains summarised social-media text).
	if result.get("explainer"):
		result["explainer"] = _wrap(result["explainer"])

	# Wrap each post's free-text fields.
	wrapped_posts: list[dict[str, Any]] = []
	for post in result.get("example_posts", []) or []:
		post_copy = dict(post)
		for key in _POST_TEXT_FIELDS:
			if post_copy.get(key):
				post_copy[key] = _wrap(post_copy[key])
		wrapped_posts.append(post_copy)
	result["example_posts"] = wrapped_posts

	return result


def _wrap(text: str) -> str:
	return f"{_OPEN_TAG}\n{text}\n{_CLOSE_TAG}"


# ---------------------------------------------------------------------------
# Regex scrubbing helpers
# ---------------------------------------------------------------------------


def _scrub_post(
	post: dict[str, Any],
	compiled: list[re.Pattern[str]],
	index: int,
) -> tuple[dict[str, Any], list[CybersecViolation]]:
	"""Scrub free-text fields of a single example post dict."""
	post_copy = dict(post)
	violations: list[CybersecViolation] = []

	for key in _POST_TEXT_FIELDS:
		value = post_copy.get(key)
		if not value:
			continue
		scrubbed, found = _scrub_text(
			str(value), compiled, field_name=f"post[{index}].{key}"
		)
		post_copy[key] = scrubbed
		violations.extend(found)

	return post_copy, violations


def _scrub_text(
	text: str,
	compiled: list[re.Pattern[str]],
	field_name: str,
) -> tuple[str, list[CybersecViolation]]:
	"""Scrub a single text value. Replaces matches with ``[REDACTED]``.

	Returns the scrubbed string and a list of violations found.
	"""
	violations: list[CybersecViolation] = []
	result = text

	for pattern in compiled:
		match = pattern.search(result)
		if match:
			matched = match.group(0)
			violations.append(
				CybersecViolation(
					field=field_name,
					pattern=pattern.pattern,
					matched_text=matched[:120],
				)
			)
			logger.warning(
				"Cybersec scrub: field=%s pattern=%r matched=%r",
				field_name,
				pattern.pattern,
				matched[:80],
			)
			result = pattern.sub("[REDACTED]", result)

	return result, violations


def _normalize_list(items: Iterable[Any]) -> list[str]:
	normalized: list[str] = []
	for item in items or []:
		value = str(item).strip()
		if value:
			normalized.append(value)
	return normalized
